export const SUBMIT_ANGRY_PROMPT = "SUBMIT_ANGRY_PROMPT"
export const SUBMIT_ANGRY_PROMPT_FAILED = "SUBMIT_ANGRY_PROMPT_FAILED"
export const SHARE_VIA_CLIPBOARD = "SHARE_VIA_CLIPBOARD"
export const SHARE_VIA_IMAGE_NOT_IMPLEMENTED = 'SHARE_VIA_IMAGE_NOT_IMPLEMENTED'
